eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8004/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: Item-Service
   
server:
  port: 8003